const mongoose = require("mongoose");
const { ObjectId } = require("mongodb");

var HomeSettingSchema = new mongoose.Schema({
  Header_Logo_image: { type: String },
  header_background_image: { type: String },
  Footer_logo_image: { type: String },
  PaymentMethod_logo: { type: String },
  About_Us_Header: { type: String },
  Categories_Header: { type: String },
  CompanyFooter: { type: String },
  ContactUs_Header: { type: String },
  FAQ_Header: { type: String },
  Featured_Categories: { type: String },
  FooterLogo: { type: String },
  Latest_Discounted_Products: { type: String },
  Latest_Products_Count: { type: mongoose.Types.Decimal128 },
  MyAccountFooter: { type: String },
  Offers_Header: { type: String },
  Payment_Method_Section: { type: String },
  Popular_Products: { type: String },
  PrivacyPolicy_Header: { type: String },
  Promotion_Banner: { type: String },
  Quick_Delivery_Section: { type: String },
  Social_Links: { type: String },
  Terms_Header: { type: String },
  TopCategoryFooter: { type: String },
  about_us: { type: String },
  categories: { type: String },
  checkout: { type: String },
  contact_us: { type: String },
  faq: { type: String },
  feature_description: { type: String },
  feature_title: { type: String },
  feature_title_Daily_Title: { type: String },
  feature_title_Daily_date: { type: String },
  footer_block_four_address: { type: String },
  footer_block_four_email: { type: String },
  footer_block_four_phone: { type: String },
  footer_block_one_link_four: { type: String },
  footer_block_one_link_four_title: { type: String },
  footer_block_one_link_one: { type: String },
  footer_block_one_link_one_title: { type: String },
  footer_block_one_link_three: { type: String },
  footer_block_one_link_three_title: { type: String },
  footer_block_one_link_two: { type: String },
  footer_block_one_link_two_title: { type: String },
  footer_block_one_title: { type: String },
  footer_block_three_link_four: { type: String },
  footer_block_three_link_four_title: { type: String },
  footer_block_three_link_one: { type: String },
  footer_block_three_link_one_title: { type: String },
  footer_block_three_link_three: { type: String },
  footer_block_three_link_three_title: { type: String },
  footer_block_three_link_two: { type: String },
  footer_block_three_link_two_title: { type: String },
  footer_block_three_title: { type: String },
  footer_block_two_link_four: { type: String },
  footer_block_two_link_four_title: { type: String },
  footer_block_two_link_one: { type: String },
  footer_block_two_link_one_title: { type: String },
  footer_block_two_link_three: { type: String },
  footer_block_two_link_three_title: { type: String },
  footer_block_two_link_two: { type: String },
  footer_block_two_link_two_title: { type: String },
  footer_block_two_title: { type: String },
  help_text: { type: String },
  latest_discount_title: { type: String },
  login: { type: String },
  logout: { type: String },
  my_account: { type: String },
  offers: { type: String },
  pages: { type: String },
  phone_number: { type: String },
  privacy_policy: { type: String },
  promotion_button_link: { type: String },
  promotion_button_name: { type: String },
  promotion_description: { type: String },
  promotion_title: { type: String },
  quick_delivery_button: { type: String },
  quick_delivery_description: { type: String },
  quick_delivery_link: { type: String },
  quick_delivery_subtitle: { type: String },
  quick_delivery_title: { type: String },
  hero_sections: [
    {
      home_Slider_Images: { type: String },
      slider_button_link: { type: String },
      slider_button_name: { type: String },
      slider_description: { type: String },
      slider_title: { type: String },
    },
  ],
  DelayShoppingProductsID: [ObjectId],
  feature_title_Daily_dicount: { type: String },
  social_facebook: { type: String },
  social_linkedin: { type: String },
  social_pinterest: { type: String },
  social_twitter: { type: String },
  social_whatsapp: { type: String },
  term_and_condition: { type: String },
  Base_Color_option: { type: String },
  Secend_Color_option: { type: String },
});
var A_P_SettingShema = mongoose.Schema({
  aboutUs: { type: String },
  privacyPolicy: { type: String },
  terms_conditions: { type: String },
});
const Check_out_schema = mongoose.Schema({
  apply_button: { type: String },
  checkout_phone: { type: String },
  city: { type: String },
  confirm_button: { type: String },
  continue_button: { type: String },
  country: { type: String },
  discount: { type: String },
  email_address: { type: String },
  first_name: { type: String },
  last_name: { type: String },
  order_summary: { type: String },
  payment_method: { type: String },
  personal_details: { type: String },
  shipping_cost: { type: String },
  shipping_details: { type: String },
  shipping_name_one: { type: String },
  shipping_name_two: { type: String },
  shipping_one_cost: { type: String },
  shipping_one_desc: { type: String },
  shipping_two_cost: { type: String },
  shipping_two_desc: { type: String },
  street_address: { type: String },
  sub_total: { type: String },
  total_cost: { type: String },
  zip_code: { type: String },

  Shipping_Methods_one_name: { type: String },
  Shipping_Methods_one_delivery: { type: String },
  Shipping_Methods_one_cost: { type: String },
  Shipping_Methods_one_price: { type: String },

  Shipping_Methods_two_name: { type: String },
  Shipping_Methods_two_delivery: { type: String },
  Shipping_Methods_two_cost: { type: String },
  Shipping_Methods_two_price: { type: String },
});
var ContactUS_SettingShema = mongoose.Schema({
  address_box_address_one: { type: String },
  address_box_title: { type: String }, 

  callUs_box_phone: { type: String }, 
  callUs_box_text: { type: String }, 
  callUs_box_title: { type: String }, 

  checked_Address_Box: { type: Boolean }, 
  checked_CallBox: { type: Boolean }, 
  checked_Contact_Form: { type: Boolean }, 
  checked_EmailBox: { type: Boolean }, 
  checked_Middle_Left_Colum: { type: Boolean }, 
  checked_bg_Hero: { type: Boolean }, 

  contact_form_description: { type: String }, 
  contact_form_title: { type: String },

  contact_page_title: { type: String }, 

  email_box_email: { type: String }, 
  email_box_text: { type: String }, 
  email_box_title: { type: String }, 

  header_background_image: { type: String }, 
  middle_left_colum_Image: { type: String }, 
});
var FAQsSettingShema = mongoose.Schema({
  FAQs_Left_Column_Image: { type: String },
  FAQs_Left_Column_checked: { type: String },
  FAQs_Page_Header_checkbox: { type: String },
  FAQs_checked: { type: String },
  FAQs_header_background_image: { type: String },
  faq_description_eight: { type: String },
  faq_description_five: { type: String },
  faq_description_four: { type: String },
  faq_description_one: { type: String },
  faq_description_seven: { type: String },
  faq_description_six: { type: String },
  faq_description_three: { type: String },
  faq_description_two: { type: String },
  faq_page_title: { type: String },
  faq_title_eight: { type: String },
  faq_title_five: { type: String },
  faq_title_four: { type: String },
  faq_title_one: { type: String },
  faq_title_seven: { type: String },
  faq_title_six: { type: String },
  faq_title_three: { type: String },
  faq_title_two: { type: String },
});
var Seo_SettingShema = mongoose.Schema({
  SeoSetting_tital: { type: String },
  SeoSetting_Description: { type: String },
  SeoSetting_Kaywords: { type: String },
  SeoSetting_url: { type: String },
  SeoSetting_image: { type: String },
});

var settingsSchema = mongoose.Schema({
  HomeSettingSchema: { type: HomeSettingSchema },
  A_P_Setting: { type: A_P_SettingShema },
  ContactUS_Setting: { type: ContactUS_SettingShema },
  FAQs_Setting: { type: FAQsSettingShema },
  Seo_Setting: { type: Seo_SettingShema },
  Check_out: { type: Check_out_schema },
});
const store_cu_md =  mongoose.model("store_coutomization", settingsSchema)

module.exports = store_cu_md;
